config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories do
    resources :tasks
  end
  
  root 'categories#index'
  # root to: 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :tasks, dependent: :destroy # this mean if category is destroy task will destroy also
    belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /categories or /categories.json
  def index
    @categories = Category.all.where(:user_id => current_user.id)
    @tasks = Task.all.where(:category_id => @categories, :schedule => (Date.today))
  end

  # GET /categories/1 or /categories/1.json
  def show
    @task = @category.tasks
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id
    
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category, :content) 
    end
end

app/controllers/covers_controller.rb
class CoversController < ApplicationController
  before_action :set_cover, only: %i[ show edit update destroy ]

  # GET /covers or /covers.json
  def index
    @covers = Cover.all
  end

  # GET /covers/1 or /covers/1.json
  def show
  end

  # GET /covers/new
  def new
    @cover = Cover.new
  end

  # GET /covers/1/edit
  def edit
  end

  # POST /covers or /covers.json
  def create
    @cover = Cover.new(cover_params)

    respond_to do |format|
      if @cover.save
        format.html { redirect_to @cover, notice: "Cover was successfully created." }
        format.json { render :show, status: :created, location: @cover }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cover.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /covers/1 or /covers/1.json
  def update
    respond_to do |format|
      if @cover.update(cover_params)
        format.html { redirect_to @cover, notice: "Cover was successfully updated." }
        format.json { render :show, status: :ok, location: @cover }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cover.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /covers/1 or /covers/1.json
  def destroy
    @cover.destroy
    respond_to do |format|
      format.html { redirect_to covers_url, notice: "Cover was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cover
      @cover = Cover.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cover_params
      params.require(:cover).permit(:image_link)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :get_category

  def index
    # @category = Category.find(task_params[:category_id])
    @tasks = @category.tasks
  end

  def show
    # @category = Category.find(params[:category_id])
    @task = @category.tasks.find(params[:id])

  end

  def new
    # @category = Category.find(params[:category_id])
    @task = @category.tasks.build
  end

  def create
    @task = @category.tasks.build(task_params)

    if @task.save
        redirect_to @category  #index page
    else
        render :new
    end
  end

  def edit
    @task = @category.tasks.find(params[:id])
  end

  def update
    @task = @category.tasks.find(params[:id])
    if  @task.update(task_params)
      redirect_to @category, notice: "Category was successfully updated."
    else
      render :show, status: :unprocessable_entit
    end
  end

    # DELETE /products/1 or /products/1.json
    def destroy
      @task = @category.tasks.find(params[:id])
      @task.destroy
      respond_to do |format|
        format.html { redirect_to [@category], notice: "Product was successfully destroyed." }
        format.json { head :no_content }
      end
    end

  private

  def get_category
      @category = Category.find(params[:category_id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :category_id, :schedule)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/covers_helper.rb
module CoversHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-signin mt-4">

    <label for="formControlInput" class="form-label"><%= form.label :category %></label>
    <%= form.text_field :category, class:"form-control", placeholder: 'Category name' %>

    <br>

    <label for="formControlInput" class="form-label"><%= form.label :content %></label>
    <%= form.text_field :content, class:"form-control", placeholder: 'Category name' %>

    <div class="d-flex justify-content-center" >
      <%= form.submit 'Save Category', class: "btn btn-primary mt-4"%>
    </div>
  </div>

<% end %>

app/views/categories/edit.html.erb
<%= render "layouts/nav" %>

<br><br>
<div class="d-flex justify-content-center">
    <h2 class="mx-4 mt-4">Editing Category</h2>
</div>

<%= render 'form', category: @category %>

<div class="d-flex justify-content-center">
    <%= link_to 'Back',  @category ,class: "btn btn-outline-secondary"%>
</div>

app/views/categories/index.html.erb
<div class="row g-0 sidebar">
  <div class="col-sm-6 col-md-10 width_full">
    <%= render "layouts/nav" %>
    <p id="notice" class="ms-4"><%= notice %></p>
    <h2 class="ms-4">Today's Tasks:</h2>
    <%= render 'tasks/task_today' %>
    </p>
  </div>

  <div class="col-6 col-md-1 category_padding width_full">
    <h3 class="my-4 category_title"><strong><u>Categories</u></strong></h3>
    <div class="container">
      <div class="d-flex justify-content-center">

        <div class="d-flex ">
          <div class="container category_below" >
            <% @categories.each do |category| %>
              <div class="card card-width-18 ms-4 my-2 category_side">
                <div class="card-body  ">
                  <strong class="card-title"><%= category.category.upcase %></strong>
                  <p class="card-text"><%= category.content.capitalize %></p>
                  <%= link_to 'Show', category, class: "btn btn-outline-primary btn-sm" %>

                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <br>

  <div class="d-flex justify-content-center"><%= link_to 'Add Category', new_category_path, class: "btn btn-primary ms-4 addcategorybtn" %></div>




  </div>
</div>

app/views/categories/new.html.erb
<%= render "layouts/nav" %>

<br><br>
<div class="d-flex justify-content-center">
    <h2 class="mx-4 my-2">New Category</h1>
</div>



<%= render 'form', category: @category %>

<div class="d-flex justify-content-center">
    <%= link_to 'Back', categories_path, class: "btn btn-outline-secondary mx-4" %>
</div>

app/views/categories/show.html.erb
<%= render "layouts/nav" %>
<p id="notice" class="ms-4"><%= notice %></p>


<div class="d-flex justify-content-between category_small">
  <div d-flex>
    <div class="ms-4 row">
      <label class="col-form-label"><h4>Category:</h4></label>
      <p class="col"><%= @category.category %></p>
    </div>
  
    <div class="ms-4 mb-1 row">
      <label class="col-form-label"><h4>Description</h4></h4></label>
      <div class="col"><%= @category.content %></div>
    </div>
  <br>
  </div>
  <div class="form-field mx-4">
    <%= link_to 'Edit', edit_category_path(@category),class: "btn btn-outline-primary" %> 
    <%= link_to 'Back', categories_path,class: "btn btn-outline-secondary" %> 
    <%= link_to 'Delete', @category, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-outline-danger" %>
  </div>
</div>

<hr>

<%= render 'tasks/task', category: @category %>
<div class="d-flex justify-content-center">
  <%= link_to 'Add new task',  new_category_task_path(@category),class: "btn btn-primary ms-4 mt-4" %>

</div>

app/views/covers/_cover.html.erb
<p>
    <!-- <strong>Image link:</strong> -->
    <%#= image_tag @cover.image_link, class: 'img-thumbnail cover' %>
</p>

app/views/covers/_form.html.erb
<%= form_with(model: cover) do |form| %>
  <% if cover.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cover.errors.count, "error") %> prohibited this cover from being saved:</h2>

      <ul>
        <% cover.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image_link %>
    <%= form.text_field :image_link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/covers/edit.html.erb
<h1>Editing Cover</h1>

<%= render 'form', cover: @cover %>

<%= link_to 'Show', @cover %> |
<%= link_to 'Back', covers_path %>

app/views/covers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Covers</h1>

<table>
  <thead>
    <tr>
      <th>Image link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @covers.each do |cover| %>
      <tr class= "row" >
        <td class="col-sm-3"><%= image_tag cover.image_link, class: 'img-thumbnail', alt: "img-thumbnail" %></td>
        <td><%= link_to 'Show', cover %></td>
        <td><%= link_to 'Edit', edit_cover_path(cover) %></td>
        <td><%= link_to 'Destroy', cover, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cover', new_cover_path %>

app/views/covers/new.html.erb
<h1>New Cover</h1>

<%= render 'form', cover: @cover %>

<%= link_to 'Back', covers_path %>

app/views/covers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image link:</strong>
  <%= @cover.image_link %>
</p>

<%= link_to 'Edit', edit_cover_path(@cover) %> |
<%= link_to 'Back', covers_path %>

app/views/layouts/_nav.html.erb
<div class="navbar navbar-expand-lg navbar-dark bg-dark", style="width: 100%;">

  <div class="d-flex justify-content-between">
    <a class="navbar-brand ms-4" href="/categories"><h3>App Journal</h3></a>
    <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> -->
    
    <div class="logout_now mx-3 mt-2">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, method: :delete ,class: "btn btn-outline-primary ms-4" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
  
  </div>

</div>

<br><br>

app/views/layouts/_task_form.html.erb
<%= form_with model: [ @category,@category.tasks.build ] do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppJournal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    <%# <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%= stylesheet_link_tag 'style.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'covers/cover' %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= render "layouts/nav" %> 

<div class="d-flex justify-content-center">
    <h2 class="mx-4 mt-4">Edit Task</h2>
</div>

</div>

<%= form_with model: [@category, @task ], local: true do |f| %>
    <p class="d-flex justify-content-center">
        <% if @task.errors.any? %>
            <ul>
                <% @task.errors.full_messages.each do |message| %>
                    <li><%= message  %></li>
                <% end %>
            </ul>
        <% end %>
    </p>
    <div class="form-signin mt-2 center_this">

    <p >
        <div>
            <b><%= f.label :name, 'Task name:', class:"form-label" %></b>
        </div>
        <%= f.text_field :name, placeholder: 'Task', class: 'name' ,class:"form-control"%>
    </p>

    <p>
        <b><%= f.label :description, 'Task description:', class:"form-label" %></b>
        <%= f.text_field :description, placeholder: 'Description', class:"form-control" %>
    </p>

    <p>
        <b><%= f.label :schedule, 'Schedule:', class:"form-label" %></b>
        <%= f.text_field :schedule, placeholder: 'YYYY-MM-DD', class:"form-control", type: "date" %>
    </p>

    <p >
        <div class="d-flex justify-content-center" >
            <%= f.submit 'Update Task', class: "btn btn-primary mt-4"%>
        </div>
    </p>

<% end %>

 

app/views/tasks/_task.html.erb
<h2 class="ms-4 mt-4">Tasks</h2>
<br>

<div class="d-flex justify-content-center">

<% @task.each do |task| %>
    <div class="card card-width-18 mx-2">
      <div class="card-body">
        <div class="card-title"><%= task.name %></div>
        <div class="card-text"><%= task.description %></div>
        <div class="card-text"><%= task.schedule %></div>
        <%= link_to 'Show', [@category, task],class: "btn btn-outline-primary btn-sm"  %>
        <%= link_to "Edit", [:edit, @category, task], class: "btn btn-outline-secondary btn-sm"  %>
        <%= link_to 'Delete', [@category, task] , method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %>
      </div>
    </div>
<% end %>
  

</div>

app/views/tasks/_task_today.html.erb
<div class="container cover px-2">
  <div id="carouselDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
    <ol class="carousel-indicators">
      <li data-bs-target="#carouselDark" data-bs-slide-to="0" class="active"></li>
      <li data-bs-target="#carouselDark" data-bs-slide-to="1"></li>
      <li data-bs-target="#carouselDark" data-bs-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item">
        <img src="https://s20427.pcdn.co/wp-content/uploads/2018/04/mood-boost-696x489.jpg" class="d-block w-100 cover_image" alt="Slide 1">
      </div>
      <div class="carousel-item active">
        <img src="https://img3.goodfon.com/wallpaper/nbig/7/ae/devochka-sarafan-priroda-6863.jpg" class="d-block w-100  cover_image" alt="Slide 2">
      </div>
      <div class="carousel-item">
        <img src="https://scienceofstory.b-cdn.net/wp-content/uploads/2017/07/mi-pham-223464-1024x683.jpg" class="d-block w-100  cover_image" alt="Slide 3">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselDark" role="button" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselDark" role="button" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </a>
  </div>  
</div>

<div class="container">
  <div class="d-flex mt-4 mx-4 rowtoday"> 
    <% @tasks.each do |task| %>
      <div class="card card-width-18 mx-2 my-2">
        <div class="card-body ">
          <div class="card-title"><strong><%= task.name.upcase %></strong></div>
          <div class="card-text text-muted"><%= task.description %></div>
        </div>
        <div class="card-footer text-muted"><%= task.schedule.strftime("%B %-d %Y") %></div>
      </div>
    <% end %>
  </div>  
</div>

app/views/tasks/edit.html.erb
<%= render "layouts/nav" %>

<%= render 'form', categories: @category %>


<div class="d-flex justify-content-center">
    <%= link_to 'Back',  @category ,class: "btn btn-outline-secondary"%>
</div>

app/views/tasks/index.html.erb
<h1>Task/index</h1>


<% @tasks.each do |task| %>
      <strong><%= task.name %></strong>
      <div><%= task.description %></div>
      <div><%= task.schedule %></div>
    <p>
      <%= link_to 'Show', [@category, task] %> |
      <%= link_to "Edit", [:edit, @category, task] %>
    </p>
<% end %>

<hr>

app/views/tasks/new.html.erb
<%= render "layouts/nav" %> 
<br>

<div class="d-flex justify-content-center">
    <h2 class="mx-4 mt-4">Create Task</h2>
</div>

</div>

<%= form_with model: [@category, @task ], local: true do |f| %>
    <p class="d-flex justify-content-center">
        <% if @task.errors.any? %>
            <ul>
                <% @task.errors.full_messages.each do |message| %>
                    <li><%= message  %></li>
                <% end %>
            </ul>
        <% end %>
    </p>
    <div class="form-signin mt-4 center_this">

    <p >
        <div>
            <b><%= f.label :name, 'Task name:', class:"form-label" %></b>
        </div>
        <%= f.text_field :name, placeholder: 'Task', class: 'name' ,class:"form-control"%>
    </p>

    <p>
        <b><%= f.label :description, 'Task description:', class:"form-label" %></b>
        <%= f.text_field :description, placeholder: 'Description', class:"form-control" %>
    </p>

    <p>
        <b><%= f.label :schedule, 'Schedule:', class:"form-label" %></b>
        <%= f.text_field :schedule, placeholder: 'YYYY-MM-DD', class:"form-control", type: "date" %>
    </p>

    <div class="d-flex justify-content-center" >
        <%= f.submit 'Add Task', class: "btn btn-primary mt-4"%>
    </div>

<% end %>

app/views/tasks/show.html.erb
<%= render "layouts/nav" %>
<p>
    <strong>Task:</strong>
    <%= @task.name %>
</p>

<p>
    <strong>Description:</strong>
    <%= @task.description %>
</p>

<%= link_to 'Back', @category %> |
<%= link_to 'Destroy', [@category, @task] , method: :delete, data: { confirm: 'Are you sure?' } %>